### ISSUE TITLE
Entity id already exists - ignoring: binary_sensor.golf_7_insured. Platform rdw does not generate unique IDs

### ISSUE THREAD

**Issue by golles** [eelcohn/home-assistant-rdw#21]
Hi,

Since a while I'm getting error messages like this:
```
Log Details (ERROR)
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:435
Integration: Binary sensor (documentation, issues)
First occurred: 12:09:02 PM (1 occurrences)
Last logged: 12:09:02 PM

Entity id already exists - ignoring: binary_sensor.golf_7_insured. Platform rdw does not generate unique IDs
```

On the configuration - integration page I had a lot of records for RDW, I deleted all beside the one with 3 entities and restarted (which game the above log) and the following UI:
![Screenshot 2020-04-30 at 12 12 20](https://user-images.githubusercontent.com/2211503/80699253-f3254b80-8adb-11ea-94a7-bd2f15429fb0.png)

Config:
```
❯ cat hass-config/packages/rdw.yaml 
rdw:
  - plate: 82ZXJ2
    name: "Golf 7"
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall

homeassistant:
  customize:
    sensor.golf_7_expdate:
      friendly_name: "APK Vervaldatum"
    binary_sensor.golf_7_insured:
      friendly_name: "Verzekeringsstatus"
    sensor.golf_7_recall:
      friendly_name: "Terugroepstatus"
  
group:
  AutoGolf7:
    name: Golf 7
    entities:
    - sensor.golf_7_expdate
    - binary_sensor.golf_7_insured
    - sensor.golf_7_recall
```
