### ISSUE TITLE
Insured as a binary sensor

### ISSUE THREAD

**Issue by metbril** [eelcohn/home-assistant-rdw#7]
Currently, the Insured state is a `sensor` and not a `binary_sensor`. For automations etc. it would be preferable to create the sensor as a type `binary_sensor`, so it can be used for logical comparisions. Using this, will also allow it to be displayed in our local language Dutch, since the True/False or On/Off etc. get translated. We can even use the device class type for sensors:

https://www.home-assistant.io/docs/configuration/customizing-devices/#device_class

My current workaround is to create an extra template binary sensor:

```yaml
binary_sensor:
  - platform: template
    sensors:
      niro_insured:
        friendly_name: "Niro Insured"
        entity_id: sensor.niro_insured
        value_template: "{{ is_state('sensor.niro_insured', 'True') }}"
```

**Comment by eelcohn** [comment]
Thank you for your feedback. I agree that `binary_sensor` would be better. I'll add it in a new release, but it's probably gonna take till the new year before I get to program this though.

**Comment by eelcohn** [comment]
Implementing this would mean moving away from setting up the RDW component as:
```
sensor:
  - platform: rdw
    plate: 16RSL9
    sensors:
      - expdate
      - insured
      - recall
```
to something like this:
```
rdw:
  - plate: 16RSL9
    binary_sensors:
      - insured
    sensors:
      - expdate
      - recall
```
I'll have to look into this if and how I want to do this.
